certinia/debug-log-analyzer

- log-viewer/modules/Analysis.js
- log-viewer/modules/Database.js
- log-viewer/modules/LineParser.js
- log-viewer/modules/Main.js
- log-viewer/modules/NamespaceExtrator.js
- log-viewer/modules/Timeline.js
- log-viewer/modules/TreeView.js
- src/Context.ts
- src/Display.ts
- src/SymbolFinder.ts
- src/commands/LoadLogFile.ts
- src/commands/LogView.ts
- src/commands/ShowLogFile.ts
- src/display/QuickPick.ts
- src/display/QuickPickWorkspace.ts
- src/sfdx/Command.ts
- src/sfdx/logs/GetLogFiles.ts
**display log (log rendering)**
Changes the analysis and rendering to happen in parallel where possible.
This improves performance especially with larger logs.
**load log file cmd executes more in parallel**
rendering the initial view and reading the log file now happen in parallel.
** show log file cmd more parallel processing**
The initial view rendering and reading the log file will now happen in parallel.
**getViewContent does more processing in parallel**
index.html + bundle.js files are loaded in parallel
#31
> feat: parallel rendering + file loading

- CHANGELOG.md
- log-viewer/modules/Main.ts
- log-viewer/modules/parsers/LineParser.ts
Ensure that some text will be shown before the time taken for all lines on the call tree.
Also fixes a few types that were mapped incorrectly in the `lineType` map.
**Before**
**After**
Fixes: #42
> bug: show text on call tree for all line types

- .github/workflows/build.yml
- .github/workflows/publish.yml
- CHANGELOG.md
- README.md
- docs/index.markdown
- log-viewer/modules/Main.ts
- log-viewer/modules/Timeline.ts
- log-viewer/modules/TreeView.ts
- log-viewer/out/index.html
- log-viewer/resources/css/TimelineView.css
- log-viewer/resources/css/TreeView.css
**Zoom on timeline**
- zoom to an accuracy of 0.001ms, time markers are shown with a ms time value and white line e.g 9600.001 ms
- scroll up and down on the mouse to zoom in and out
- zoom is based on position of mouse pointer, ensuring that position is kept on screen when zoomed in or out
- scroll left and right on the mouse to move the time line left are right, when zoomed
- click the mouse down and drag to move the timeline around both in the x and y direction, when zoomed
resolves: #33
> feat: zoom on timeline

- log-viewer/modules/components/CallStack.ts
- log-viewer/modules/components/DatabaseRow.ts
All methods after the first line were indented to the left.
The have been shifted to the right so they align with the first line in the callstack.
I have not created an entry in the changelog since this was a fix for a new feature introduced in develop after v1.3.4 release.
fixes: #69
> fix: align all callstack with first line in database view

- .github/workflows/build.yml
- .github/workflows/publish.yml
- log-viewer/modules/Timeline.ts
- log-viewer/resources/css/TimelineView.css
Add the right edge of the screen the tooltip would shrink to be unreadable.
It will now be pushed left instead and retain size.
This was not a regression and was introduced in develop after v1.3.4 was released.
So not adding it to changelog, unless there is an objection.
fixes: #71
> fix: tooltip to always stay on screen

- CHANGELOG.md
- log-viewer/modules/TreeView.ts
This is not a perfect solution as the content will not be scrolled to top in all cases.
If the screen size is small or the view size has been reduced this will not work correctly.
resolves: #73
> feat: calltree scroll until content stuck to top

- CHANGELOG.md
- lana/package.json
- log-viewer/modules/Timeline.ts
- log-viewer/modules/parsers/LineParser.ts
- log-viewer/modules/parsers/TreeParser.ts
- `FLOW_START_INTERVIEWS` log lines on the calltree and timeline will show either the Process Builder or Flow name after the chunk number 
**Process builders**
Calltree
Timeline
**Flow**
Calltree
Timeline
resolves #68
> feat: add pb and flow names in timeline + calltree

- CHANGELOG.md
- log-viewer/modules/Analysis.ts
- log-viewer/modules/Main.ts
- log-viewer/modules/Timeline.ts
- log-viewer/modules/__tests__/LineParser.test.ts
- log-viewer/modules/parsers/LineParser.ts
The total time on the status bar will be the time between `EXECUTION_STARTED` and `EXECUTION_FINISHED`.
Previously the end time would use the last valid line in the log which in some cases would be `CUMULATIVE_PROFILING` resulting in the total time being wrong on status and analysis tab as well as the timeline having some blank space at the end.
The total time is not taken from the `EXECUTION_STARTED` in the treeparser instead of the total duration in the lineparser.
The `EXECUTION_STARTED` node is the first child node of the root node.
> bug: incorrect end time

- .github/workflows/tests.yml
- CHANGELOG.md
- log-viewer/jest.config.js
- log-viewer/modules/__tests__/Analysis.test.ts
- log-viewer/modules/__tests__/Database.test.ts
- log-viewer/modules/__tests__/LineParser.test.ts
- log-viewer/modules/__tests__/TreeView.test.ts
- log-viewer/modules/__tests__/Util.test.ts
- log-viewer/modules/parsers/LineParser.ts
Previously the log parser would only handle LF (\n) line endings.
Now it will handle both CRLF (\r\n) + LF (\n) via the regex `/\r?\n/`
- Line parser handles both CRLF (\r\n) + LF (\n) via the regex `/\r?\n/`
fixes #108
> bug: line parser split handle CRLF + LF line endings

- CHANGELOG.md
- lana/src/commands/LoadLogFile.ts
- lana/src/sfdx/Command.ts
- lana/src/sfdx/logs/GetLogFiles.ts
- log-viewer/modules/Database.ts
- Rounds the log size on the `Log: Load APEX Log for Analysis` output list to 2DP
- Rearranges content to be more similar to the SF SFDX version of the command to make this more familiar when switching between them.
**New**
**Old**
resolves #91
> feat: round log size

- log-viewer/modules/TreeView.ts
- log-viewer/out/index.html
Firstly, I love this extension, made life so easy in debugging and backtracking the code without endless ctrl + f (like finding a needle in the haystack). 
This change adds a filter to the call tree providing an ability to hide details of methods, queries that take less time (in ms). This may help users identify the problem method/query faster by hiding unnecessary details. Users can control the time by specifying in a number input.
resolves #112
> Ability to filter call tree based on time taken

- log-viewer/modules/Main.ts
child array length can change so length can not be assigned to a var.
Bug introduced in #119 
fixes #90
> fix: length of children

- CHANGELOG.md
- lana/.gitignore
- lana/src/SymbolFinder.ts
- lana/src/commands/LoadLogFile.ts
- lana/src/commands/LogView.ts
- lana/src/commands/ShowLogFile.ts
- lana/src/sfdx/logs/GetLogFile.ts
- Improved performance getting log file from an org when using the `Log: Load Apex Log For Analysis` command
- Switch using `writeFile` for `--outputdir` in the `force:apex:log:get` sfdx command. 
The force:apex:log:get implementation uses a writestream which is faster.
a 20mb log will download and display in ~12s instead of ~20s (on my machine)
resolves #123
> feat: Improved performance getting log file from an org when using the `Log: Load Apex Log For Analysis` command

- .prettierrc
- CHANGELOG.md
- lana/.gitignore
- log-viewer/.gitignore
- log-viewer/modules/Timeline.ts
- log-viewer/modules/parsers/LineParser.ts
- log-viewer/modules/parsers/TreeParser.ts
- Makes it easier to differentiate between "Flows" and "Process Builders" in the timeline and call tree 
- (Process Builder) or (Flow) shown after the `FLOW_START_INTERVIEWS` event line e.g `FLOW_START_INTERVIEWS : Account Process Builder (Process Builder) - 478.274ms (self 1.925ms)`
- (Process Builder) or (Flow) shown on the timeline tooltip for `FLOW_START_INTERVIEWS` event. 
resolves #114
> feat: More easily differentiate between "Flows" and "Process Builders" in the timeline and call tree 

- .github/workflows/publish.yml
- CHANGELOG.md
- lana/package.json
build(publish): add step to publish to Open VSX Registry
- Updates the publish workflow to also publish to the Open VSX Registry
This is the marketplace used by Salesforce Code Builder and will allow the analyzer to be used from Code Builder.
It is an open source alternative to vscode marketplace.
https://open-vsx.org/
- Update publish.yml to publish to Open vsx registry
resolves #23
> build(publish): publish to Open VSX Registry

- CHANGELOG.md
- lana/package-lock.json
- lana/package.json
- log-viewer/modules/Timeline.ts
Fixes the setting of custom colors on the timeline from vscode settings.
- Fixes the custom color preferences from vscode not being used
- Fix color prefs fro vscode settings not being used
- Update release
- Update change log
fixes #163
> fix: custom colors for timeline from vscode prefs - v1.5.1

- CHANGELOG.md
- lana/package-lock.json
- lana/package.json
- log-viewer/modules/Timeline.ts
Fixes the setting of custom colors on the timeline from vscode settings.
- Fixes the custom color preferences from vscode not being used
- Fix color prefs fro vscode settings not being used
- Update release
- Update change log
fixes #163
> bug: fix custom timeline colors merge to main

- .github/workflows/build.yml
- .github/workflows/publish.yml
- .github/workflows/tests.yml
- update the node + checkout actions to v3. These should be more stable.
resolves #163
> ci: update node + checkout actions to v3

- log-viewer/modules/Main.ts
This pull requests adds a new message capability in order to send log without having a file.
This is used in the context of a browser extension I am developing to display trace directly in the developer tools (https://github.com/swisscat/sf-xp-debugger). The log-viewer is used within an iframe and is passed the log contents.
- Added new message 'streamLog'
resolves #168
> feat: Added message functionality to pass stream log data

- CHANGELOG.md
- log-viewer/modules/Main.ts
- log-viewer/modules/TreeView.ts
- log-viewer/modules/__tests__/TreeParser.test.ts
- log-viewer/modules/parsers/TreeParser.ts
If the events occured outside the `EXECUTION_STARTED` + `EXECUTION_FINISHED`
events they would not be shown.
We now use the last event with a duration and exitStamp for the exittime / duration.
The reason we check for a duration and do not just take the last event
is that an event without a duration is not going to be shown on the timeline
and in all likely hood is simply information and does not contribute towards
execution time.
fixes #180
> bug: some timeline events with duration not shown

- log-viewer/modules/TreeView.ts
- log-viewer/resources/css/TreeView.css
fix: breadcrumb text being unreadable on dark themes
The background was always light but the text color changes to light on dark themes and was therefore unreadable
- Makes the breadcrumbs readable for dark themes
fixes #142
> fix: breadcrumb text being unreadable on dark themes

- lana/package.json
- log-viewer/modules/Analysis.ts
- log-viewer/modules/Timeline.ts
- log-viewer/modules/__tests__/TreeParser.test.ts
- log-viewer/modules/parsers/TreeParser.ts
This was due to the endtime being used a the last log element with a duration. Now there are two properties on root for time
`executionEndTime` which is the endtime of the last node with a duration (the latest time that should be shown on timeline) `exitStamp` which is the end time of the lastest node regardless of duration.
This means the total time of the log will sometimes be different to the timeline time if there are log lines that show extra info e.g `CUMULATIVE_USAGE`
fixes #180
> fix: some rows not expanding on calltree

- CHANGELOG.md
- lana/src/sfdx/logs/GetLogFile.ts
fix: Spaces not supported in output directory path
When running `Log: Load Apex Log For Analysis` command
fixes #187
> fix(v1.5.0) Spaces not supported in output directory path

- .github/workflows/publish.yml
ci: fix publish build
- Ensure ovsx is installed correctly by doing separate installs, multiple installs does not seem to be working.
- Fix typo `-no-dependencies` should be `--no-dependencies`
- Fix typi when running `ovsx` it should not have been `osvx`
> ci: fix publish build

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/publish.yml
- BUILDING.md
- README.md
- jest.config.js
- log-viewer/modules/__tests__/Database.test.ts
- log-viewer/modules/__tests__/SOQLParser.test.ts
- log-viewer/modules/__tests__/TreeView.test.ts
- log-viewer/package.json
- package.json
The url for https://vsmarketplacebadges.apphd/ got changed to https://vsmarketplacebadges.dev/
so we need to update it to get the badges working again.
Alternatively we could use https://shields.io/ as they have the same badges
See https://github.com/cssho/VSMarketplaceBadge/issues/18#issuecomment-1284739771 and https://github.com/microsoft/vscode-react-native/pull/1893/files for more info
resolves #207
> chore: fix badge urls

- log-viewer/modules/Main.ts
- log-viewer/modules/__tests__/TreeParser.test.ts
- log-viewer/modules/components/CallStack.ts
- log-viewer/modules/parsers/TreeParser.ts
Improves performance pf processing `ENTERING_MANAGED_PKG` events
Processing 20000 `ENTERING_MANAGED_PKG` events goes from ~4.5s to ~94ms
Mainly done by replacing editing current child list with `splice` to overriding the child array with an assignment instead
It also means a `ENTERING_MANAGED_PKG` event will span the whole of a `METHOD_ENTRY` event and will cause nesting
Since the `ENTERING_MANAGED_PKG` is generally noise when you can see the content (via subscriber).
It probably makes more sense to remove the `ENTERING_MANAGED_PKG` events if there are other children e.g we can see the namespace method calls for the managed package anyway .
> chore: ENTERING_MANAGED_PKG performance

- CHANGELOG.md
- README.md
- log-viewer/modules/Timeline.ts
- Adds the row count to the timeline tooltip for any event what has one.
- e.g `SOSL`, `SOQL` + `DML` events
- This includes showing 0 when appropriate.
resolves #129
> feat: add rowcount to timeline tooltip for `SOSL`, `SOQL` + `DML` events

- CHANGELOG.md
- log-viewer/resources/css/Settings.css
- log-viewer/resources/css/Status.css
- log-viewer/resources/css/TimelineView.css
- log-viewer/resources/css/TreeView.css
- Ensure fonts scale consistently in all screens.
- Before the font on the header would not scale when changed in vscode
**Before: font size 20**
**Fixed: font size 20** 
fixes #238
> bug: fonts not consistently scaling

- CHANGELOG.md
- log-viewer/modules/Timeline.ts
- log-viewer/modules/Util.ts
- Fixes the timeline tooltip to remain visible when scrolling
- Also improves performance by adding debounce on scroll and mouse move that will ensure the tootlip is only rendered on the next animation frame.
fixes #242
> bug: timeline tooltip disappears on zoom

- CHANGELOG.md
- lana/package.json
- package-lock.json
- Updates the minimum supported version of vscode to 1.74.0
This is the version in which the [activation events change](https://code.visualstudio.com/updates/v1_74#_implicit-activation-events-for-declared-extension-contributions) occurred 
- This includes updating the the type definitions to match.
resolves #280
> chore: update vscode minimum supported engine to v1.74.0

- config/tsconfig.json
- lana/package.json
- lana/rollup.config.mjs
- lana/tsconfig.json
- log-viewer/package.json
- log-viewer/rollup.config.mjs
- log-viewer/tsconfig.json
- package-lock.json
- package.json
- rollup.config.mjs
- use swc to transpile ts to js instead of tsc, because it is much faster.
- tsc is run as a lint step to address type issues.
resolves #287
> chore: switch tsc  to swc for transpiling

- CHANGELOG.md
- README.md
- lana/package.json
- lana/src/Context.ts
- lana/src/codelenses/ShowAnalysisCodeLens.ts
- lana/src/commands/RetrieveLogFile.ts
- lana/src/commands/ShowLogAnalysis.ts
Renames the `Log: Load Apex Log For Analysis` command to `Log: Retrieve Apex Log And Show Analysis`
This makes it generally clearer what it does  and that it will get the log from an org and 
resolves #288
> feat: rename load apex log command to `Log: Retrieve Apex Log And Show Analysis`

- CHANGELOG.md
- lana/src/Display.ts
- lana/src/display/OpenFileInPackage.ts
- Uses [`vscode.open`](https://code.visualstudio.com/api/references/commands) to open logs larger than 50MB.
The previous way was to use `[showTextDocument](https://code.visualstudio.com/api/references/vscode-api#window)` which has a 50MB limit
resolves #254
> feat: open large logs

- .husky/pre-commit
- CHANGELOG.md
- lana/src/commands/LogView.ts
- log-viewer/modules/analysis-view/AnalysisView.ts
- log-viewer/modules/datagrid/dataaccessor/Number.ts
- log-viewer/modules/services/VSCodeService.ts
- package.json
- pnpm-lock.yaml
- Copy data to clipboard directly from Analysis grid by focusing on the grid and using ctrl + c or cmd + c
- Export to CSV file using the `Export to CSV` action in the grid header menu 
resolves #25
**Copied to sheet from clipboard**
**Export to CSV**
> feat: export to csv from analysis table

- log-viewer/modules/Main.ts
- log-viewer/modules/parsers/TreeParser.ts
If the log can not be fetch from local disk,
will now show an error in the status bar.
> feat: show an error if log not found

- log-viewer/modules/calltree-view/CalltreeView.ts
- log-viewer/modules/datagrid/module/RowKeyboardNavigation.ts
Improves the call tree keyboard navigation
- Auto select a row If a row is expanded or collapsed and no row is currently selected.
- Ensure tableholder gets focus when a row is expanded / collapsed with the tree toggle, this allows the keys for row selection to be used.
resolves #297
> feat: select row when tree expanded/collapsed

- CHANGELOG.md
- log-viewer/modules/analysis-view/AnalysisView.ts
- log-viewer/modules/database-view/DatabaseView.ts
- log-viewer/modules/datagrid/module/RowKeyboardNavigation.ts
- Analysis: keyboard navigation ([#294][#294])
- Keyboard navigation to move between selected rows. Use the up and down arrows for up and down
- Database: keyboard navigation ([#294][#294])
- Keyboard navigation to move between selected rows. Use the up and down arrows for up and down. Left and right arrows will hide / show the detail panel,
resolves #294
fixes #312
> feat : db + analysis row navigation

- CHANGELOG.md
- log-viewer/modules/__tests__/TreeParser.test.ts
- log-viewer/modules/parsers/TreeParser.ts
This now means some events will no longer be
rolled up into `ENTERING_MANAGED_PKG`
e.g `SOQL_BEGIN` will be between two
`ENTERING_MANAGED_PKG` events instead of
nested inside one
fixes #320
> fix: `ENTERING_MANAGED_PKG` events would wrongly have other events rolled up into them

- log-viewer/index.html
- log-viewer/modules/datagrid/module/RowNavigation.ts
- log-viewer/resources/css/AnalysisView.css
- log-viewer/resources/css/TreeView.css
- The end of the row would overflow becoming hidden behind the scrollbar.
resolves #297
> fix: Call Tree expand overflow

- CHANGELOG.md
- log-viewer/modules/components/CallStack.ts
- Fixes go to call tree from the SOQL call stack
- Related Issue #
- fixes #346 
- resolves #
- closes #
> fix: go to call tree from the SOQL call stack

- CHANGELOG.md
- lana/package.json
fix open log code lense not showing
The code lense would not show until the extension
was activated using one of the commands at least once
- Related Issue #
- fixes #340 
- resolves #
- closes #
> bug: fix open log code lense not showing

- .github/workflows/publish.yml
chore: verify marketplace tokens are valid
Before trying to publish we should ensure that both tokens are valid. This prevents publishing to vsce and not ovsx.
- `vsce verify-pat -p` + `ovsx verify-pat -p`
> chore: verify marketplace tokens are valid

- .github/workflows/publish.yml
chore: verify marketplace tokens are valid
Before trying to publish we should ensure that both tokens are valid. This prevents publishing to vsce and not ovsx.
- `vsce verify-pat -p` + `ovsx verify-pat -p`
> chore: verify marketplace token are valid

- .github/workflows/cd-prerelease.yml
Will now publish at 4:15AM to reduce the risk of the job being dropped.
_Note: The schedule event can be delayed during periods of high loads of GitHub Actions workflow runs. High load times include the start of every hour. If the load is sufficiently high enough, some queued jobs may be dropped. To decrease the chance of delay, schedule your workflow to run at a different time of the hour._
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
Related Issue #300 
fixes #
resolves #
closes #
No
> chore: update pre release schedule time

- .github/workflows/cd-prerelease.yml
- .github/workflows/imgcmp.yml
The image optimization job and scheduled pre release should only run in the main repo and not forks.
fixes #
resolves #
closes #
> chore: disable some workflows for forks

- CHANGELOG.md
- log-viewer/modules/app-header/AppHeader.ts
- log-viewer/modules/components/LogTitle.ts
- log-viewer/modules/navbar/NavBar.ts
- log-viewer/modules/notification.styles.css
- log-viewer/modules/notifications/NotificationButton.ts
- log-viewer/modules/notifications/NotificationPanel.ts
- log-viewer/modules/notifications/NotificationTag.ts
- log-viewer/modules/parsers/TreeParser.ts
Moves the log issues from inside the navbar as a long horizontal list.
Now show an issue count tag with a panel the displays the issues as a vertical list when clicked.
Related Issue #249 #247
fixes #
resolves #
closes #
> feat: navbar issue count

- log-viewer/modules/analysis-view/AnalysisView.ts
- log-viewer/modules/calltree-view/CalltreeView.ts
- log-viewer/modules/components/BadgeBase.ts
- log-viewer/modules/database-view/DatabaseSection.ts
- log-viewer/modules/database-view/DatabaseView.ts
- log-viewer/modules/navbar/NavBar.ts
- log-viewer/modules/notifications/NotificationTag.ts
Related Issue #247, #249 
fixes #
resolves #
closes #
> perf: table tabs render improvements

- CHANGELOG.md
- lana/src/commands/LogView.ts
- Fixes `export to CSV` to work when a log is opened and no workspace is selected
if a log was open and unattached to a workspace `export to csv` would fail to work.
fixes #363 
resolves #
closes #
> bug: export to csv when no workspace is selected

- CHANGELOG.md
- lana/package.json
- lana/src/commands/LogView.ts
- rollup.config.mjs
Show the Certinia logo next to the Open Log Analyzer tab and next to the file name on the file list in the quick open menu 
fixes #
resolves #250 
closes #
> feat: add certinia icon to webview

- log-viewer/modules/components/LogTitle.ts
- log-viewer/modules/global.styles.ts
fixes  hyperlink underline styles accidentally removed
Related Issue #252 
fixes #
resolves #
closes #
> fix: hyperlink underline styles accidentally removed

- CHANGELOG.md
- lana/src/Context.ts
- lana/src/WhatsNewNotification.ts
- log-viewer/modules/calltree-view/CalltreeView.ts
- log-viewer/modules/timeline/Timeline.ts
Shows an vscode info notification when the extension first runs.
Includes a what' new button to take the user to the change log.
This will only run if it is not a bug fix version e.g v1.10.0 + v1.11.0 it will be shown but not for v1.10.1
If the notification has already been shown it will not be show again for the current version.
fixes #
resolves #210 
closes #
- [] 🙅 not needed
> feat: whats new notification

- .eslintrc.json
- package.json
- pnpm-lock.yaml
chore: stop prettier running via eslint to check files are formatted
Prettier will  normally run on save in vscode and 
will run again when files are committed via lint-staged.
So files should always be correctly formatted and do not need to be checked.
`prettier --check` will now be run in parallel to eslint in CI instead.
- Remove `eslint-plugin-prettier`
- Runs `prettier --check` in CI instead of via eslint
fixes #
resolves #
closes #
> chore: stop prettier running via eslint to check files are formatted

- CHANGELOG.md
- lana/src/Display.ts
- lana/src/commands/LogView.ts
- lana/src/commands/RetrieveLogFile.ts
- lana/src/commands/ShowLogAnalysis.ts
- log-viewer/modules/LogViewer.ts
- log-viewer/modules/log-levels/LogLevels.ts
- log-viewer/modules/navbar/NavBar.ts
**show error modal if log does not exist**
If the log file does not exist when retrieve or show is
called an error modal will be show in the vscode ui.
for retrieve this will only be shown after the log
download finishes and therefore should only occur if
there is an issues with the file download.
**show error when file can not be found**
This will be shown in the error list on the 
log viewer UI when the file can not be read 
from file system.
fixes #435 
resolves #
closes #
> bug: UI hanging if file does not exist

- CHANGELOG.md
- log-viewer/modules/database-view/DatabaseView.scss
- log-viewer/modules/database-view/DatabaseView.ts
fix: improve the reliability of scroll when rows are clicked
The behaviour of keeping the grouped and normal rows that 
are clicked in focus should be far more reliable.
This should reduce the jumping effect that can be seen 
with tables of a large height.
fixes #434 
resolves #
closes #
> bug: database UI jumping on group expand

- CHANGELOG.md
- log-viewer/modules/components/LogViewer.ts
- log-viewer/modules/components/notifications/NotificationPanel.ts
- log-viewer/modules/styles/notification.styles.ts
- log-viewer/modules/timeline/Timeline.ts
Changes Skipped-Lines and Max-Size-reached marker color from green to blue. Green normal mean things are ok, blue better represents information.
Adds faint grey lines between the event markers to seperates them. This helps when two error are next to each other.
fixes #
resolves #115 
closes #
> feat: timeline global info markers improvements

- CHANGELOG.md
- lana/src/commands/LogView.ts
- lana/src/commands/RetrieveLogFile.ts
- lana/src/commands/ShowLogAnalysis.ts
feat: open viewer with editor content if file does not exist
This is mainly to support drag and drop file in code builder.
It also helps when a file is deleted on local disk or a log is 
copy and pasted into an editor window without saving.
fixes #
resolves #213 
closes #
> feat: open viewer from dirty editor

- CHANGELOG.md
- log-viewer/modules/__tests__/ApexLogParser.test.ts
- log-viewer/modules/components/LogViewer.ts
- log-viewer/modules/components/calltree-view/CalltreeView.ts
- log-viewer/modules/parsers/ApexLogParser.ts
- package.json
This is adding support to show more events inside the `Workflow:ApprovalProcessActions` code unit
It will also support showing event on the timeline that have now explicit end node but can use following like events to estimate one (looped events). These are both entry and exit nodes.
These are pseudo entry / exit lines and use the timestamp of the next non detail line as their exit. As such this may lead to over estimates in some cases.
**add support for pseudo exit lines**
These lines will use the next lines timetamp as their exit time.
But only if the next line is also a pseudo exit, an exit or an entry.
**show FLOW_START_INTERVIEW_BEGIN lines in timeline**
Related Issue #228 #211 
fixes #
resolves #336 #211
closes #
> feat: parser add duration for some events without end

- CHANGELOG.md
- lana/package.json
chore: update version 1.12.0 release
Wait until 2023-12-05 to merge and release.
> chore: update version 1.12.0 release

- CHANGELOG.md
- lana/package.json
- lana/src/commands/LogView.ts
fixes unable to Save file when exporting CSV from Analysis or Database
Seems to be a specific windows issue.
Needed to use URI.fsPath and not URI.path
fixes #461 
resolves #
closes #
> bug: save file exception windows

- .github/workflows/cd-prerelease.yml
- .github/workflows/publish.yml
The ovsx cli behaves differently when --packagePath is passed compared to vsce. It causes the package command in vsce to be called again and and extension vsix re created.
fixes #
resolves #
closes #
> ci: fix publish jobs

- .github/workflows/cd-prerelease.yml
ci: fix --skip-duplicate being ignored on ovsx stage
> chore: fix --skip-duplicate being ignored on ovsx stage

- log-viewer/modules/__tests__/ApexLogParser.test.ts
- log-viewer/modules/parsers/ApexLogParser.ts
- Generally improves parser performance.
- The main change is to remove recursion from the aggregate totals function
- Add a fast path for getting commonly used event types
- Add a fast path for splitting new lines when the line endings are all lf e.g `\n`
Total parse time: from 2.02s -> 1.95s 
toTree: ~1022ms -> 1025 ms
parseLog: ~974-> 750 ms
fixes #
resolves #
closes #
- [X ] 🙅 not needed
> feat: parser performance

- log-viewer/modules/components/AnalysisView.ts
- log-viewer/modules/parsers/ApexLogParser.ts
- log-viewer/modules/timeline/Timeline.ts
More parser performance improvements.
The gets the parse time for a given log down from 2.87s to 0.916s in the best case
Related Issue #475 
fixes #
resolves #
closes #
> Perf: parser speed

- CHANGELOG.md
- lana/package.json
- bump release version to v1.14.0
- Update release date in changelog
fixes #
resolves #
closes #
> chore: bump release version to v1.14.0

- .github/workflows/cd-prerelease.yml
- .github/workflows/ci.yml
- .github/workflows/publish-gh-pages.yml
- .github/workflows/publish.yml
- CHANGELOG.md
Mainly due to gh actions retiring use of node 16 in favour of 20 due to EOL.
fixes #
resolves #
closes #
> chore: update github actions to latest version

- CHANGELOG.md
- lana/src/salesforce/codesymbol/SymbolFinder.ts
- log-viewer/modules/__tests__/SOQLParser.test.ts
- log-viewer/modules/__tests__/soql/SOQLLinter.test.ts
- log-viewer/modules/components/SOQLLinterIssues.ts
- log-viewer/modules/soql/SOQLLinter.ts
- log-viewer/modules/soql/SOQLParser.ts
- rollup.config.mjs
Splits som of the deps into separate js bundle files for faster load.
This comes in two parts. On the vscode extension side  and the log viewer side. 
1. @apexdevtools/apex-ls
2. @apexdevtools/apex-parser
3. antlr4ts
@apexdevtools/apex-ls is only used when clicking on a link in the call tree to go to code, so can be loaded later.
Initial load of the vscode extension is now ~6ms instead of ~100 ms. 
This means the webview is shown sooner and everything feels faster.
fixes #
resolves #
closes #
> perf: use code splitting for faster initial load

- CHANGELOG.md
- lana/package.json
- lana/src/salesforce/logs/GetLogFile.ts
- lana/src/salesforce/logs/GetLogFiles.ts
- rollup.config.mjs
fix retrieve log file cmd not working
Caused by the minification step and dynamic imports 
but the easiest fix is to remove the dynamic imports.
Dev and test is done on un minified code which is why it was not spotted.
fixes #490 
resolves #
closes #
> fix: retrieve log cmd

- log-viewer/modules/__tests__/ApexLogParser.test.ts
- log-viewer/modules/__tests__/soql/SOQLLinter.test.ts
- log-viewer/modules/parsers/ApexLogParser.ts
- Removes need for CurrentParser var in the ApexLogParser
fixes #
resolves #
closes #
> refactor: remove need for CurrentParser state

- CHANGELOG.md
- log-viewer/modules/components/find-widget/FindWidget.ts
Fixes  find in files keybinding triggering search in log analyzer
When the log analyzer webview had focus this hijacked the find in files vscode search and focused the analyzer search.
fixes #537 
resolves #
closes #
> fix: find in files keybinding triggering search in log analyzer

- CHANGELOG.md
- data/fflib.log
- log-viewer/modules/components/AnalysisView.ts
Changes the TotalTime column to show max time. 
This is more accurate but will not show an accurate number until we change the logic to sum unique paths in the stack.
Filtering could easily break this. 
For example filter by namespace and now the only two methods in the analysis are siblings 
Method 1 in pkg1 calls to Method2 and Method 3 in pkg2
Filter by pkg2 and both Method2 and Method3 should be included in the total with this change only the largest will be.
There will be a follow fix to be accurate
Related Issue #526
fixes #
resolves #
closes #
> fix: analysis total time overstated - show max time

- log-viewer/modules/__tests__/ApexLogParser.test.ts
- log-viewer/modules/components/AnalysisView.ts
- log-viewer/modules/components/analysis-view/column-calcs/CallStackSum.ts
- log-viewer/modules/parsers/ApexLogParser.ts
analysis total time sum unique stacks
Collect the stacks and only sum the unique entries e.g
If we have an analysis like this
methodA: 5s
methodB: 3s
methodC: 2s
Sibling Methods
The three methods are at the same level directly called from EXECUTION_STARTED.
All 3 should be summed as they are in different stacks.
Total: 10s
Child Methods
methodB is a child of methodA and methodC is a sibling of methodA.
we first add methodA to the total but the total for methodB has already been accounted by including methodA so we skip it and any other children of methodA.
methodC is in a unique stack and needs to be added to the total.
Total: 7s
fixes #526 
resolves #
closes #
> fix: analysis total time overstated

- log-viewer/modules/parsers/ApexLogParser.ts
Speeds up regex searching for EXECUTION_STARTED line by 668% (7.68X) faster
Mainly faster in the case when the log has no `EXECUTION_STARTED` line
Roughly the same time when `EXECUTION_STARTED` is near the start.
When no EXECUTION_STARTED is in the log perf is ~22ms vs ~169ms for a 72MB log.
fixes #
resolves #
closes #
> perf: speed up regex searching for EXECUTION_STARTED line

- log-viewer/modules/components/calltree-view/CalltreeView.ts
- speed up getAllTypes for types filter by ~1000% (12x faster)
~421ms vs ~35ms for a 71MB log.
~1,240ms vs ~62ms for 100mb log
fixes #
resolves #
closes #
> perf: calltree speed up getalltypes

- lana-docs-site/babel.config.js
- lana-docs-site/docusaurus.config.ts
- lana-docs-site/package.json
- pnpm-lock.yaml
chore: enabled docusaurus faster for fast doc builds
Speed up build times of docs from ~40s to ~10s
https://docusaurus.io/blog/releases/3.6#docusaurus-faster
fixes #
resolves #
closes #
> chore: enabled docusaurus faster for fast doc builds

- package.json
- pnpm-lock.yaml
chore: update rollup + deps
rollup: 4.28.1 -> 4.29.1
@rollup/plugin-commonjs: 25.0.8 -> 28.0.2
@rollup/plugin-node-resolve: 15.3.1 -> 16.0.0
rollup-plugin-swc3: 0.11.2 -> 0.12.1
fixes #
resolves #
closes #
> chore: update rollup + deps

- log-viewer/modules/Util.ts
- log-viewer/modules/components/AppHeader.ts
- log-viewer/modules/components/analysis-view/AnalysisView.ts
- log-viewer/modules/components/analysis-view/column-calcs/CallStackSum.ts
- log-viewer/modules/components/calltree-view/CalltreeView.ts
- log-viewer/modules/components/database-view/DMLView.ts
- log-viewer/modules/components/database-view/SOQLView.ts
perf: delays some of the rendering of tab content until tab switch.
This is to improve performance of timeline render.
resolves #553
fixes #
closes #
> perf: delays some of the rendering of tab content until tab switch

- CHANGELOG.md
- log-viewer/modules/components/calltree-view/CalltreeView.ts
- log-viewer/modules/components/calltree-view/module/Find.ts
- log-viewer/modules/components/calltree-view/module/MiddleRowFocus.ts
- log-viewer/modules/components/database-view/DMLView.ts
- log-viewer/modules/components/database-view/SOQLView.ts
- Fix a regression in the render performance of the call tree
- The find formatter applied to each row was always executing after each animation frame via `requestAnimationFrame` (RAF) regardless of whether there could possibly be any text to highlight (no search had been done), this is now skipped unless needed.
- The `MiddleRowFocus` was always adding `setTimeout` to the task queue event if there was no row to focus on, this is now skipped unless needed.
fixes #581 
resolves #
closes #
> bug(perf): regression in call tree render performance

- CHANGELOG.md
- README.md
- lana-docs-site/docs/docs/features.md
- log-viewer/modules/components/analysis-view/AnalysisView.ts
- log-viewer/modules/components/database-view/DMLView.ts
- log-viewer/modules/components/database-view/SOQLView.ts
- log-viewer/modules/components/datagrid/datagrid-filter-bar.ts
- Move action buttons from the  kebab menu (three vertical dots) on table column header to icons buttons above and to the right of the table.
This makes it easier and more obvious to use.
fixes #
resolves #583
closes #
> feat: table action buttons

- CHANGELOG.md
- log-viewer/modules/components/analysis-view/AnalysisView.ts
- log-viewer/modules/components/calltree-view/CalltreeView.ts
- Fixes an issue where the analysis table would disappear when the scroll pill was dragged halfway down.
The fix is a bit of a hack as `datatree:true` seems to resolve it even when there is not a datatree.
Needs fixing in downstream Tabulator.
- Change 1
- Change 2
fixes #590
resolves #
closes #
related #
> fix: analysis table table vanishing on scroll drag

- CHANGELOG.md
- log-viewer/modules/components/calltree-view/CalltreeView.ts
- log-viewer/modules/components/calltree-view/module/Find.ts
- log-viewer/modules/components/calltree-view/module/MiddleRowFocus.ts
- log-viewer/modules/datagrid/module/RowKeyboardNavigation.ts
- call tree search will now only search within the filtered visible rows only.
It used to search in non visible rows which was misleading to step through results and show nothing, It was also slow.
fixes #
resolves #539 
closes #
related #
> feat: call tree search within filtered visible rows only

- log-viewer/package.json
- pnpm-lock.yaml
-  tabulator-tables: 6.3.0 -> 6.3.1
- @types/tabulator-tables: 6.2.3 -> 6.2.6
fixes #
resolves #
closes #
related #
> chore: update tabulator-tables to v6.3.1

- log-viewer/modules/components/analysis-view/AnalysisView.ts
- log-viewer/modules/components/calltree-view/CalltreeView.ts
- log-viewer/modules/components/database-view/DMLView.ts
- log-viewer/modules/components/database-view/SOQLView.ts
- log-viewer/modules/datagrid/groups/GroupCalcs.ts
- log-viewer/modules/datagrid/groups/GroupSort.ts
- Group sorting did not work in all cases.
- Avoided using some private methods in tabulator which prevents internal tabulator state being polluted.
fixes #
resolves #
closes #
related (#592, #593 )
> fic: group sorting not working

- log-viewer/modules/components/LogViewer.ts
- log-viewer/modules/parsers/ApexLogParser.ts
- log-viewer/modules/timeline/Timeline.ts
Improves performance when reading the log file + parsing it.
- ⚡ Switch from array and includes to check content to a Set and has
- ⚡Speed up `nodesToRectangles`, `flattenByDepth `, `getMaxDepth` by reducing loops, completed avoid calling get + set on map per node.
fixes #
resolves #
closes #
related #
> perf: improve apex log parser speed

- LICENSE.txt
- README.md
Add attribution to Readme for using tabulator tables
- Change 1
- Change 2
fixes #
resolves #
closes #
related #
> docs: add attribution for tabulator tables

- log-viewer/modules/components/analysis-view/AnalysisView.ts
- log-viewer/modules/components/calltree-view/CalltreeView.ts
- log-viewer/modules/components/database-view/DMLView.ts
- log-viewer/modules/components/database-view/SOQLView.ts
The search logic in the grid was causing an infinite loop when calling expand/ collapse all on calltree.
The find search handling has been refactored to block clearing search highlights when search is happening and only clear if a rerender occurs and no search is currently active.
This means search highlights only clear when grouping, sorting etc (anything the causes a render other than search).
- Change 1
- Change 2
fixes #
resolves #
closes #
related #581
> fix: calltree expand performance regression due to search recursion

- log-viewer/modules/components/analysis-view/AnalysisView.ts
- log-viewer/modules/components/calltree-view/CalltreeView.ts
- log-viewer/modules/components/calltree-view/module/Find.ts
- log-viewer/modules/components/database-view/DMLView.ts
- log-viewer/modules/components/database-view/SOQLView.ts
stop search from occurring multiple times
- Change 1
- Change 2
fixes #
resolves #
closes #
related #
> fix: stop search from occurring multiple times

- log-viewer/modules/components/analysis-view/AnalysisView.ts
- log-viewer/modules/components/calltree-view/CalltreeView.ts
- log-viewer/modules/components/calltree-view/module/Find.ts
- log-viewer/modules/components/database-view/DMLView.ts
- log-viewer/modules/components/database-view/DatabaseView.ts
- log-viewer/modules/components/database-view/SOQLView.ts
Find correctly searches inside grouped data again
- Change 1
- Change 2
fixes #
resolves #
closes #
related #592
> fix: find to work in groups

- CHANGELOG.md
- lana/package.json
- log-viewer/modules/Util.ts
- log-viewer/modules/__tests__/ApexLogParser.test.ts
- log-viewer/modules/__tests__/Util.test.ts
- log-viewer/modules/components/CallStack.ts
- log-viewer/modules/components/analysis-view/AnalysisView.ts
- log-viewer/modules/components/analysis-view/column-calcs/CallStackSum.ts
- log-viewer/modules/components/calltree-view/CalltreeView.ts
- log-viewer/modules/datagrid/format/Progress.ts
- log-viewer/modules/datagrid/format/ProgressComponent.ts
- log-viewer/modules/datagrid/format/ProgressMS.ts
- log-viewer/modules/datagrid/style/DataGrid.scss
- log-viewer/modules/parsers/ApexLogParser.ts
- log-viewer/modules/timeline/Timeline.ts
- log-viewer/modules/timeline/TimelineView.ts
- Add formatting for cumulative limit usage in the call tree.
- Always show the cumulative limit usage rows (even though time is 0)
- Add percentage bars in cells that use cumulative limit usage totals for the percent.
- DML + SOQL rows, DML + SOQL statements 
- Show governor limits totals on timeline tooltip e.g 1000/50000 for row s
-show tooltip on call tree and analysis grid to show Governor totals e.g 4000/10000 for dml rows.
-
fixes #
resolves #308 
resolves #309
closes #
related #
> feat:  governor limit reporting

- .github/workflows/cd-prerelease.yml
- .github/workflows/ci.yml
- .github/workflows/publish-gh-pages.yml
- .github/workflows/publish.yml
- .npmrc
- DEVELOPING.md
- lana/package.json
- pnpm-lock.yaml
Updates lana (vscode extension) node version to v22 which is vscode latest supported version
Updates node version in workflows to v22
Updates pnpm version in github workflows to v10
fixes #
resolves #
closes #
related #
> chore: bump node to v22
