build.sbt
lana/dist/CHANGELOG.md
lana/dist/package.json
lana/src/main/scala/com/financialforce/lana/commands/ShowLogFile.scala
lana/src/main/scala/com/financialforce/lana/runtime/vscode/Types.scala
lana/src/main/scala/com/financialforce/lana/workspace/Workspace.scala

Use fsPath instead of path for Windows compatibility

---

lana/src/main/scala/com/financialforce/lana/commands/ShowLogFile.scala

Handle no uri being passed to ShowLogFile command

---

lana/src/main/scala/com/financialforce/lana/Context.scala
lana/src/main/scala/com/financialforce/lana/commands/ShowLogFile.scala
lana/src/main/scala/com/financialforce/lana/display/QuickPickWorkspace.scala
lana/src/main/scala/com/financialforce/lana/runtime/vscode/Types.scala

Length exception

---

build.sbt
lana/dist/package-lock.json
lana/dist/package.json
lana/src/main/scala/com/financialforce/lana/Context.scala
lana/src/main/scala/com/financialforce/lana/SymbolFinder.scala
lana/src/main/scala/com/financialforce/lana/display/OpenFileInPackage.scala
lana/src/main/scala/com/financialforce/lana/workspace/VSWorkspace.scala

Cut over to npm version of pkgforce

---

.vscodeignore
log-viewer/package-lock.json
package-lock.json
package.json
rollup.config.js
tsconfig.json

This will minify all js + tree shake js from node_modules.
Reduces extension size from ~20mb to ~4mb.
#30

feat: bundle extension by applying rollup

---

CHANGELOG.md
log-viewer/modules/TreeView.ts

Fixes hide details, hide system calls + hide formulas on the call tree
**Before**
**After**
fixes #45

bug: call tree fix hide details hide system calls

---

CHANGELOG.md
docs/index.markdown
log-viewer/modules/Analysis.ts
log-viewer/modules/Timeline.ts
log-viewer/modules/TreeView.ts
log-viewer/modules/Util.ts
log-viewer/modules/__tests__/Analysis.test.ts
log-viewer/modules/__tests__/LineParser.test.ts
log-viewer/modules/__tests__/TreeView.test.ts
log-viewer/modules/__tests__/Util.test.ts
log-viewer/modules/parsers/LineParser.ts
log-viewer/out/index.html
log-viewer/resources/css/AnalysisView.css

- Add support (at least to detail level) for all know log events as detailed [here](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_debugging_system_log_console.htm)
- Rename `Net Duration` to `Self Time` and `Total Duration` to `Total Time` this should be clearer for users to understand.
- Fixed an issue where user debug log would not correctly handle multi line text from the log
resolves #81

feat support all known event types

---

CHANGELOG.md
lana/package-lock.json
lana/package.json

- change package.json version to v1.4.0
- change CHANGELOG.md version to v1.4.0
@kjonesffdc Do I need an issue for this change?

Chore update log analyzer version v1.4.0

---

lana/package-lock.json
lana/package.json

Includes a fix for opening classes in a
windows project with a forceignore file.

chore: update pkgforce dep to v2.1.4

---

CHANGELOG.md
lana/.gitignore
lana/.vscodeignore
lana/package-lock.json
lana/package.json

- add missing readme + changelog to extension
- update version v1.4.1

Chore update version v1.4.1

---

CHANGELOG.md
lana/package-lock.json
lana/package.json

change package.json version to v1.4.2
change CHANGELOG.md version to v1.4.2

chore: update version v1.4.2 for release

---

CHANGELOG.md
docs/index.markdown
log-viewer/modules/TreeView.ts
log-viewer/out/index.html
log-viewer/resources/css/TreeView.css

- Makes the hide under filter apply the filter as the checkbox is checked / unchecked so that it is not only on first expand.
That way when the filter is selected everything is shown again instead of remaining hidden.
- Also adds new feature info to chnagelog + doc update
resolves #104

feat: calltree duration filter

---

CHANGELOG.md
lana/package-lock.json
lana/package.json

change package.json version to v1.5.0
change CHANGELOG.md version to v1.5.0

chore: update version v1.5.0

---

CHANGELOG.md

docs: update changelog for v1.5.0

docs: update changelog for v1.5.0

---

CHANGELOG.md

- Updates the release date for v1.5.0 to 2022-08-08

docs: update changelog release date

---

CHANGELOG.md
lana/package-lock.json
lana/package.json

chore: update version v1.5.2 for release

chore: update version v1.5.2

---

.github/workflows/build.yml
.github/workflows/ci.yml
CHANGELOG.md
lana/package.json
lana/src/sfdx/logs/GetLogFile.ts
log-viewer/modules/Timeline.ts
log-viewer/modules/parsers/TreeParser.ts

Merges the v1.5.2 release changes into main

chore: merge 1.5.2 to main

---

CHANGELOG.md

Update changelog to show new analysis view features
resolves #294

docs: new analysis view - update changelog

---

log-viewer/modules/Timeline.ts
log-viewer/modules/TreeView.ts
log-viewer/modules/__tests__/TreeParser.test.ts
log-viewer/modules/calltree-view/CalltreeView.ts
log-viewer/modules/database-view/DatabaseSection.ts
log-viewer/modules/database-view/DatabaseView.ts
log-viewer/modules/parsers/TreeParser.ts

- Tooltip will show the total (self + children) as well as self rows for this this event, DML / SOQL event)
- Calltree show the totalRows in the row column
resolves #297

feat: add selfRowCount

---

docs/index.markdown

- update help for v1.7 release to match the content in 
https://github.com/certinia/debug-log-analyzer/blob/main/README.md

docs: update help for v1.7 release

---

CHANGELOG.md
lana/package.json

Update the changelog + package.json to v1 .7.0

docs: update version for 1.7.0 release

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/chore.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

- Adds auto labelling to created issues
- bug template: 'bug', 'needs-triage'
- feature template: 'enhancement', 'needs-triage'
- Add chore issue template for issues that do not fit into bug/ feature.
resolves #313

chore: auto label issues

---

CHANGELOG.md

Add missing change for issue 255
Improve performance of `Log: Retrieve Apex Log And Show Analysis`

docs: update changelog for missing change - v1.7.0

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/chore.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

- Reminders to update the documentation mostly, but also some emojis added.

chore: add more information to pr template

---

CHANGELOG.md
lana/package.json

chore: merge 1.7.1 to main

---

CHANGELOG.md

docs: fix 1.7.1 release date
- Related Issue #
- fixes #
- resolves #
- closes #

docs: fix 1.7.1 release date

---

.github/workflows/cd-prerelease.yml

fix: remove tput in echo
can not be used in gitactions
Related Issue #300 
fixes #
resolves #
closes #

chore: fix tput in echo

---

.github/workflows/cd-prerelease.yml

[- Briefly describe **what** the pull request does](fix: remove bold formatting)

fix: remove bold formatting

---

.github/workflows/cd-prerelease.yml

chore: add echos for debug
- Change 1
- Change 2
Related Issue #300 
fixes #
resolves #
closes #

chore: add echos for debug

---

.github/workflows/cd-prerelease.yml

chore: check if pre tag exists

chore: check if pre tag exists

---

.github/workflows/cd-prerelease.yml

chore: add outputs back so second stage can run

chore: add outputs back so second stage can run

---

.github/workflows/cd-prerelease.yml

fix: pre release build should use pnpm

fix: pre release build should use pnpm

---

.github/workflows/cd-prerelease.yml
.github/workflows/publish.yml

fix: vsix path was incorrect

---

.github/workflows/cd-prerelease.yml

chore: update pre tag when it already exists
Related Issue #300 
fixes #
resolves #
closes #

chore: update pre tag when it already exists

---

log-viewer/modules/database-view/DatabaseView.scss
log-viewer/modules/database-view/DatabaseView.ts

fix: update use css class
It was not correctly updated during the css rename
Related Issue #256 
fixes #
resolves #
closes #

fix: update use css class

---

scripts/pre-release.js

chore: change pre release version format
The date part will now be two characters.
e.g 20230101 instead of 2023011
fixes #
resolves #
closes #

chore: change pre release version format

---

.github/workflows/image-optimize.yml

allow img optimize  workflow to be run manually
fixes #
resolves #
closes #

chore: allow img optimize to be run manually

---

CHANGELOG.md
log-viewer/modules/analysis-view/AnalysisView.ts
log-viewer/modules/calltree-view/CalltreeView.ts
log-viewer/modules/calltree-view/TreeView.scss
log-viewer/modules/components/CallStack.ts
log-viewer/modules/database-view/DatabaseView.ts
log-viewer/modules/datagrid/style/DataGrid.scss
log-viewer/modules/navbar/NavBar.ts

Re styles hyperlinks to match vscode styling
- No underscore by default
- Underscore will show on hover
fixes #
resolves #248
closes #

feat: restyle hyperlinks

---

log-viewer/modules/log-levels/LogLevels.ts

Previously we would hide them in the nav bar if the level is none. It is more useful to show all of them.
Related Issue #249 
fixes #
resolves #
closes #

feat: show all log levels

---

CHANGELOG.md
lana/src/commands/LogView.ts
lana/src/commands/RetrieveLogFile.ts
lana/src/commands/ShowLogAnalysis.ts
log-viewer/index.html
log-viewer/modules/LogViewer.ts
log-viewer/modules/Main.ts
log-viewer/modules/app-header/AppHeader.ts
log-viewer/modules/calltree-view/CalltreeView.ts
log-viewer/modules/services/VSCodeService.ts

Display Ui outline while waiting for other actions for both `Log: Retrieve Apex Log And Show Analysis` and `Log: Show Apex Log Analysis`
- This could be waiting for the log to download from the org or to be parsed and processed.
- A ui outline will be rendered first
- Once the DOM is ready a fetch log event is fired to the vscode side.
- The log details will the be send via an event to the log viewer side once they are ready (This could be waiting for the log to download). 
Related Issue #252 
fixes #
resolves #
closes #

feat: better progressive render

---

CHANGELOG.md
lana/src/commands/RetrieveLogFile.ts
log-viewer/modules/LogViewer.ts
log-viewer/modules/analysis-view/AnalysisView.ts
log-viewer/modules/app-header/AppHeader.ts
log-viewer/modules/calltree-view/CalltreeView.ts
log-viewer/modules/components/BadgeBase.ts
log-viewer/modules/components/LogTitle.ts
log-viewer/modules/components/skeleton/GridSkeleton.ts
log-viewer/modules/components/skeleton/skeleton.styles.ts
log-viewer/modules/database-view/DatabaseView.ts
log-viewer/modules/log-levels/LogLevels.ts
log-viewer/modules/navbar/NavBar.ts
log-viewer/modules/timeline/TimelineView.ts

**Adds skeleton loading**
- to the badges on the nav bar
- to the analysis, database + call tree table 
- and to the timeline
This is most useful when using `Log: Retrieve Apex Log And Show Analysis`
fixes #
resolves #252
closes #

feat: skeleton loading Uis

---

lana/src/commands/LogView.ts
log-viewer/index.html
log-viewer/modules/analysis-view/AnalysisView.ts
log-viewer/modules/app-header/AppHeader.ts
log-viewer/modules/calltree-view/CalltreeView.ts
log-viewer/modules/database-view/DatabaseView.ts
log-viewer/modules/navbar/NavBar.ts
log-viewer/modules/styles/codicon.css
log-viewer/package.json
pnpm-lock.yaml
rollup.config.mjs

- add codicon icons to tabs
- adopt vscode button +checkbox styles
[exmaple](https://github.com/microsoft/vscode-extension-samples/blob/69333818a412353487f0f445a80a36dcb7b6c2ab/webview-codicons-sample/src/extension.ts)
Related Issue #247 
fixes #
resolves #
closes #

feat: add codicon icons to tabs

---

log-viewer/modules/LogViewer.ts
log-viewer/modules/notifications/NotificationPanel.ts
log-viewer/modules/parsers/TreeParser.ts

Add an expandable section with more info about the issue. This could be just the stack trace or an explainer of what skipped lines mean.
Add an expandable section with more info about the issue. 
This could be just the stack trace or an explainer of 
what skipped lines mean.
fixes #
resolves #393
closes #

feat: add more detail to error notifications

---

CHANGELOG.md
log-viewer/modules/analysis-view/AnalysisView.ts
log-viewer/modules/calltree-view/CalltreeView.ts
log-viewer/modules/components/CallStack.ts
log-viewer/modules/components/SOQLLinterIssues.ts
log-viewer/modules/database-view/DatabaseView.scss
log-viewer/modules/database-view/DatabaseView.ts
log-viewer/modules/datagrid/style/DataGrid.scss

- Database View tweaks 
- Show full SOQL/ DML text instead of truncating
- Show the detail panel by default, including call stack and SOQL issues.
- Database, Call Tree and Analysis View
- New sort icon (up and down arrow) when a column is in an unsorted state
fixes #
resolves #279 
closes #

feat: db table improvements

---

CHANGELOG.md
log-viewer/modules/analysis-view/AnalysisView.ts
log-viewer/modules/database-view/DatabaseView.ts

Allows for the full soql / long methods to be more easily viewed.
Related Issue #279 
fixes #
resolves #
closes #

feat: event text on analysis view will be wrapped instead of truncating

---

CHANGELOG.md
lana/package.json

- Version number changed to v1.10.0
- Changelog release date updated
fixes #
resolves #
closes #
-  [X] 🔖 CHANGELOG.md

chore: update version for v1.10.0 release

---

log-viewer/package.json
pnpm-lock.yaml

build(deps): bump lit to v3
- Change 1
- Change 2
fixes #
resolves #
closes #

chore: bump lit to v3

---

CHANGELOG.md
lana/package.json
log-viewer/modules/calltree-view/CalltreeView.ts
log-viewer/modules/parsers/TreeParser.ts

Fixes Call Tree not showing `USER_DEBUG` content 
fixes #429 
resolves #
closes #

bug: call tree debug text not shown

---

CHANGELOG.md
lana/package.json
lana/src/commands/LogView.ts
lana/src/commands/RetrieveLogFile.ts
lana/src/commands/ShowLogAnalysis.ts
lana/src/display/Display.ts
log-viewer/modules/components/LogLevels.ts
log-viewer/modules/components/LogViewer.ts
log-viewer/modules/components/NavBar.ts
log-viewer/modules/components/calltree-view/CalltreeView.ts
log-viewer/modules/components/database-view/DatabaseView.scss
log-viewer/modules/components/database-view/DatabaseView.ts

chore: merge 1.10.2 to main

---

CHANGELOG.md
lana/package.json
package.json
pnpm-lock.yaml

chore: merge 1.10.3 to main

---

log-viewer/modules/components/AnalysisView.ts
log-viewer/modules/components/LogViewer.ts
log-viewer/modules/components/calltree-view/CalltreeView.ts
log-viewer/modules/components/database-view/DatabaseView.ts
log-viewer/modules/datagrid/dataaccessor/Number.ts
log-viewer/modules/datagrid/filters/MinMax.ts

Replaces usage of any with a type
fixes #
resolves #
closes #

chore: add typings instead of using any

---

CHANGELOG.md
log-viewer/modules/components/calltree-view/CalltreeView.ts

- Adds debug only filtering to the call tree
- Will show only debug statements with the context of the call tree
fixes #
resolves #86 
closes #

feat: Call Tree debug only filter

---

lana/src/Context.ts
lana/src/codelenses/ShowAnalysisCodeLens.ts
log-viewer/modules/__tests__/ApexLogParser.test.ts
log-viewer/modules/components/AnalysisView.ts
log-viewer/modules/components/LogViewer.ts
log-viewer/modules/components/calltree-view/CalltreeView.ts
log-viewer/modules/components/database-view/DatabaseSection.ts
log-viewer/modules/components/database-view/DatabaseView.ts
log-viewer/modules/parsers/ApexLogParser.ts
log-viewer/modules/timeline/Timeline.ts

Adds a class for self and total times.
Adopted for duration, rowCount, soqlCount, dmlCount
Related Issue #228 
fixes #
resolves #
closes #

feat: parser duration rollups

---

CHANGELOG.md
lana/src/Context.ts
lana/src/commands/LogView.ts
lana/src/commands/RetrieveLogFile.ts
lana/src/commands/ShowLogAnalysis.ts
lana/src/display/OpenFileInPackage.ts
lana/src/salesforce/codesymbol/SymbolFinder.ts

- Simplifies Go to File multiple workspace handling
Go to file from Call Tree, to only ask you to select a workspace if more than one matching file is found in multiple workspaces.
fixes #
resolves #202 
closes #

feat: open file multi workspace

---

CHANGELOG.md
lana/package.json
lana/src/commands/LogView.ts

chore: merge 1.12.1 to main

---

.github/workflows/cd-prerelease.yml
.github/workflows/publish.yml

disable deps checks when publishing to vsce + ovsx

chore: disable deps checks when publishing to vsce + ovsx

---

data/fflib.log

chore: add namespace to example log for testing
fixes #
resolves #
closes #

chore: add namespace to example log

---

rollup.config.mjs

fix: chunk files being overwritten

---

CHANGELOG.md
lana/src/salesforce/codesymbol/SymbolFinder.ts
lana/src/salesforce/logs/GetLogFile.ts
lana/src/salesforce/logs/GetLogFiles.ts
log-viewer/modules/soql/SOQLParser.ts
rollup.config.mjs

Use dynamic import and code splitting to load larger dependencies only when needed . 
Improves performance by reducing the amount of JS that is loaded and parsed at the start.
fixes #
resolves #
closes #

perf: code splitting for faster extension load

---

.github/workflows/cd-prerelease.yml
.github/workflows/ci.yml
.github/workflows/publish-gh-pages.yml
.github/workflows/publish.yml

chore: update gh workflow node version to 20
fixes #
resolves #
closes #

chore: update gh workflow node version to 20

---

CONTRIBUTING.md
lana-docs-site/docs/community/support.md
lana-docs-site/docs/docs/intro.md
lana-docs-site/docusaurus.config.ts

Fix broken docusaurus links
fixes #
resolves #
closes #

docs: fix broken links

---

CHANGELOG.md
README.md
lana-docs-site/docs/docs/usage.md
lana/package.json

- From the button on the editor title menu
- From the tab context menu (right clicking the editor tab)
fixes #
resolves #506 
closes #

feat: more ways to open the log analysis

---

log-viewer/modules/datagrid/module/RowKeyboardNavigation.ts
log-viewer/modules/datagrid/module/RowNavigation.ts
log-viewer/package.json
pnpm-lock.yaml

Update tabulator to latest v6 this should address and number of rendering issues in grids.
Related Issue #500 
fixes #
resolves #
closes #

build(deps) : update tabulator to v6

---

log-viewer/modules/components/calltree-view/CalltreeView.ts
log-viewer/modules/components/calltree-view/module/MiddleRowFocus.ts
log-viewer/modules/datagrid/module/RowNavigation.ts

Makes the go to row more reliable. 
It did not always wait for the table to be visible before scrolling.
Related Issue #481
fixes #
resolves #
closes #

feat: more reliable go to row

---

log-viewer/modules/components/database-view/DMLView.ts
log-viewer/modules/components/database-view/DatabaseSOQLDetailPanel.ts
log-viewer/modules/components/database-view/DatabaseView.scss
log-viewer/modules/components/database-view/DatabaseView.ts
log-viewer/modules/components/database-view/SOQLView.ts

- Add datatree icons
- Ensure the soql issues panel maintains a min width so it does not become unreadable on small screens
fixes #
resolves #
closes #

feat: larger soql details view

---

lana-docs-site/package.json
lana/package.json
log-viewer/package.json
pnpm-lock.yaml

build: update deps to version compatible versions
Mainly
@apexdevtools/apex-ls": "^5.0.0" :"@apexdevtools/apex-ls": "^5.2.0",
"@apexdevtools/apex-parser": "^3.5.0" : "@apexdevtools/apex-parser": "^3.6.0"
fixes #
resolves #
closes #

build: update deps to version compatible versions

---

log-viewer/modules/components/database-view/DMLView.ts
log-viewer/modules/components/database-view/SOQLView.ts

ensure soql + dml views do not overlap on db view
fixes #
resolves #
closes #

fix: ensure soql + dml views do not overlap on db view

---

CHANGELOG.md
README.md
lana-docs-site/docs/docs/features.md
lana/src/display/WebView.ts
log-viewer/modules/components/AnalysisView.ts
log-viewer/modules/components/AppHeader.ts
log-viewer/modules/components/LogViewer.ts
log-viewer/modules/components/calltree-view/CalltreeView.ts
log-viewer/modules/components/calltree-view/module/Find.ts
log-viewer/modules/components/database-view/DMLView.ts
log-viewer/modules/components/database-view/DatabaseView.ts
log-viewer/modules/components/database-view/SOQLView.ts
log-viewer/modules/components/find-widget/FindWidget.ts
log-viewer/modules/datagrid/module/RowNavigation.ts
log-viewer/modules/datagrid/style/DataGrid.scss
log-viewer/modules/styles/global.styles.ts
log-viewer/modules/timeline/Timeline.ts
log-viewer/modules/vscode-ui/VsIconCheckbox.ts

- Add  Find on Timeline, Call Tree, Analysis and Database
**Timeline**
- CMD/CTRL + f to open find
- Events with matching text are highlighted, there is a different highlight for the current match.
- Previous match, next match and case sensitive search all supported.
- If the next matching event is off screen that event will be centered on the timeline.
- The find will match on Event Type or text in the event
**Call Tree**
- CMD/CTRL + f to open find
- Any matching text is highlighted, there is a different highlight for the current match.
- Previous match, next match and case sensitive search all supported.
- If the next matching text is within a parent that parent will be expanded.
**Analysis**
- CMD/CTRL + f to open find
- Any matching text is highlighted, there is a different highlight …

feat: Find on Timeline, Call Tree, Analysis and Database

---

log-viewer/modules/timeline/Timeline.ts

find highlights clear on tab switch
Related Issue #488 
fixes #
resolves #
closes #

fix: find highlights clear on tab switch

---

log-viewer/modules/components/calltree-view/CalltreeView.ts
log-viewer/modules/components/calltree-view/module/Find.ts
log-viewer/modules/components/calltree-view/module/MiddleRowFocus.ts
log-viewer/modules/timeline/Timeline.ts

- Ensure that the findwidget shows correct totals.
Timeline find was always returning results.
- Change 1
- Change 2
fixes #
resolves #
closes #

feat: ensure that the findwidget shows correct totals

---

CHANGELOG.md
log-viewer/modules/components/calltree-view/module/Find.ts

- Resolves some issues in search on Analysis, Call tree and Database grids of results not being highlighted consistently.
fixes #536 
resolves #
closes #

bug: search has inconsistent results

---

.github/ISSUE_TEMPLATE/bug_report.md

- add section for attaching log to bug issue template
fixes #
resolves #
closes #

chore: add section for attaching log to bug issue template

---

log-viewer/modules/components/AnalysisView.ts
log-viewer/modules/components/calltree-view/CalltreeView.ts
log-viewer/modules/components/database-view/DMLView.ts
log-viewer/modules/components/database-view/SOQLView.ts

- Clear search highlights when filter changes.
Related Issue 
fixes #536 
resolves #
closes #

fix: search inconsistent results

---

CHANGELOG.md
lana/package.json
package.json

-  bump release to v1.16.1 read for release
fixes #
resolves #
closes #

chore: bump release to v1.16.1

---

lana-docs-site/docs/docs/features.md

- docs: fix broken anchors in lana site docs
fixes #
resolves #
closes #

docs: fix broken anchors in lana site docs

---

lana-docs-site/package.json
pnpm-lock.yaml

- update docusaurus-search-local to v0.46.1
fixes #
resolves #
closes #

build: update docusaurus-search-local to v0.46.1

---

lana-docs-site/package.json
pnpm-lock.yaml

- Update docusaurus to [v3.6.3](https://docusaurus.io/blog/releases/3.6)
- Enables [docusaurus faster](https://docusaurus.io/blog/releases/3.6#docusaurus-faster)
- Reduces doc site build time from 40s to 9s
fixes #
resolves #
closes #

build(deps): update docusaurus to v3.6.3

---

log-viewer/package.json
pnpm-lock.yaml

build: update lit to v3.2.1
fixes #
resolves #
closes #

build: update lit to v3.2.1

---

log-viewer/modules/datagrid/module/RowKeyboardNavigation.ts
log-viewer/package.json
pnpm-lock.yaml

update tabulator-tables to v6.3.0
resolves #551
fixes #
closes #
Related Issue

build: update tabulator-tables to v6.3.0

---

lana/package.json
pnpm-lock.yaml

Huge performance improvements
Support for api v61 + v62
Various Fixes
fixes #
resolves #
closes #

chore: update apex-ls to v5.7.0

---

lana-docs-site/package.json
pnpm-lock.yaml

update doc site deps to v3.7
fixes #
resolves #
closes #

build: update doc site deps to v3.7

---

log-viewer/package.json
pnpm-lock.yaml

chore: update apex parser to v4.4.0
fixes #
resolves #
closes #

chore: update apex parser to v4.4.0

---

log-viewer/modules/components/calltree-view/CalltreeView.ts

go to row not working from timeline to calltree
- Change 1
- Change 2
fixes #
resolves #
closes #

fix: go to row not working from timeline to calltree

---

CHANGELOG.md
log-viewer/modules/components/CallStack.ts
log-viewer/modules/components/analysis-view/AnalysisView.ts
log-viewer/modules/components/calltree-view/CalltreeView.ts
log-viewer/modules/components/database-view/DMLView.ts
log-viewer/modules/components/database-view/SOQLView.ts
log-viewer/modules/datagrid/module/RowKeyboardNavigation.ts

- Allow text to be highlighted and copied to clipboard in the table
resolves #504
fixes #
closes #

feat: enable selecting text and copy to clipboard

---

CHANGELOG.md
log-viewer/modules/components/CallStack.ts

-  fix the Call stack on DB view to show items vertically instead of horizontally
fixes #582 
resolves #
closes #

fix: Call stack on DB view shows items horizontally instead of vertically

---

CHANGELOG.md
log-viewer/modules/Main.ts
log-viewer/modules/components/analysis-view/AnalysisView.ts
log-viewer/modules/components/calltree-view/CalltreeView.ts
log-viewer/modules/components/database-view/DMLView.ts
log-viewer/modules/components/database-view/SOQLView.ts
log-viewer/modules/datagrid/group-calcs/GroupCalcs.ts
log-viewer/modules/datagrid/style/DataGrid.scss

- Moves the group totals into the the grouped rows instead of being a separate row.
- Applies to both AnalysisView + DB view. 
fixes #
resolves #583 
closes #

feat: column totals in group rows

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/chore.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

- Add emojis to issue title.
- Auto add Bug, Feature and Task types to issues
fixes #
resolves #
closes #

chore: issue + pr template improvements 

---

lana-docs-site/package.json
pnpm-lock.yaml

- @easyops-cn/docusaurus-search-local:  0.46.1 -> 0.49.2
- react: 18.3.1 -> 19.1.0
- react-dom: 18.3.1 -> 19.1.0
fixes #
resolves #
closes #
related #

chore: update lana doc site deps

---

lana/package.json
log-viewer/package.json
pnpm-lock.yaml

lana
@typescript-eslint/eslint-plugin: 8.18.1 -> 8.30.1 @typescript-eslint/parser: 8.18.1 -> 8.30.1
typescript: 5.7.2 -> 5.8.3
log-viewer
@typescript-eslint/eslint-plugin: 8.18.1 -> 8.30.1 @typescript-eslint/parser: 8.18.1 -> 8.30.1
concurrently: 9.1.0 -> 9.1.2
postcss: 8.4.49 -> 8.5.3
sass: 1.78.0 -> 1.86.3
typescript: 5.7.2 -> 5.8.3
fixes #
resolves #
closes #
related #

chore: update dev deps

---

lana/package.json
log-viewer/package.json
pnpm-lock.yaml

- update @types/node to 18.15.3 -> 20.14.8
- downgrade sass: ^1.86.3 -> ~1.78.0
fixes #
resolves #
closes #
related #

chore: update @types/node to 20.14.8

---

package.json
pnpm-lock.yaml

chore: update prettier estlint to 10.1.2
fixes #
resolves #
closes #
related #

chore: update prettier estlint to 10.1.2

---

log-viewer/package.json
pnpm-lock.yaml

- chore: update lite from 3.2.1 to 3.3.0
fixes #
resolves #
closes #
related #

chore: update lite from 3.2.1 to 3.3.0

---

lana/package.json
pnpm-lock.yaml

- chore: update apex-ls to v5.9.0
fixes #
resolves #
closes #
related #

chore: update apex-ls to v5.9.0

---

README.md

Fixes the markdown links in the readme
fixes #
resolves #
closes #
related #

docs: fix markdown links

---

lana-docs-site/docs/docs/features/analysis.md
lana-docs-site/docs/docs/features/find.md
lana-docs-site/docs/docs/features/timeline.md
lana-docs-site/docs/docs/gettingstarted.md
lana-docs-site/docs/docs/settings.md
lana-docs-site/src/pages/index.md

docs: fix broken image urls
fixes #
resolves #
closes #
related #616

docs: fix broken image urls

---

README.md

Fix some broken image links.
There was a typo in the url it should have been `/assets/` + not `/assests/`
fixes #
resolves #
closes #
related #

chore: fix img links

---

lana-docs-site/docusaurus.config.ts

fix favicon links
fixes #
resolves #
closes #
related #

chore: fix favicon links

---

lana-docs-site/docusaurus.config.ts

fix syntax issue
fixes #
resolves #
closes #
related #

chore: fix syntax issue

---

log-viewer/modules/__tests__/soql/SOQLLinter.test.ts
log-viewer/modules/parsers/ApexLogParser.ts
log-viewer/modules/parsers/LogEvents.ts
log-viewer/modules/parsers/LogLineMapping.ts
log-viewer/modules/timeline/Timeline.ts

Improve performance by
1. Avoifding creating a copy of the log string after finding the EXECUTION_STARTED line.
2. Faster loop when aggregating totals
3. null checks to skip some assignments.
fixes #
resolves #
closes #
related #

perf: log parser improved performance
